### ISSUE TITLE
Broken Manifest

### ISSUE THREAD

**Issue by Norc** [johanDa9u/Show-all-players#1]
Hello, I get a URL when i try this manifest link from your release announcement:

https://raw.githubusercontent.com/johanDa9u/Show-all-players/main/module.json%EF%BB%BF.

This may or may not be your issue, I've seen Foundry do weird things with this before. Also notifying them.

**Comment by Norc** [comment]
Update from Foundry staff as a possible cause/solution:

> possibly related to how they are saving files:
> EF BB BF is the UTF-8 encoding Byte Order Mark (BOM). I suspect there is some configuration option to turn off the BOM.
> 
> Edit: File editors should allow you to turn off the BOM when saving an file in relevant character encodings (e.g. UTF-8).

**Comment by johanDa9u** [comment]
Hello!

Thanks for reporting this. I think it was a problem with foundry since I
just put the exact same manifest link again and it seems to work now.
